version: '3.9'

services:
  frontend:
    build: 
      context: ./frontend
      args:
        REACT_APP_BASE_URL: http://localhost
        REACT_APP_API_PORT: 3001
    ports:
      - "80:80"
    depends_on:
      - backend
    #     condition: service_healthy
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - DATABASE_URL=postgres://meuguruuser:meugurupassword@host.docker.internal:5433/meuguru-db?schema=public
      - JWT_SECRET=secret
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "--silent", "--output", "/dev/null", "--head", "--request", "GET", "http://host.docker.internal:3001"]
    #   interval: 20s
    #   timeout: 20s
    #   retries: 5
    #   start_period: 20s
  db:
    image: postgres:14
    restart: always
    container_name: db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: meuguruuser
      POSTGRES_DB: meuguru-db
      POSTGRES_PASSWORD: meugurupassword
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 20s