version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - DATABASE_URL=postgres://meuguruuser:meugurupassword@host.docker.internal:5433/meuguru-db?schema=public
      - JWT_SECRET=secret
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: postgres:14
    restart: always
    container_name: db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: meuguruuser
      POSTGRES_DB: meuguru-db
      POSTGRES_PASSWORD: meugurupassword
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 20s